### ISSUE TITLE
GitHub project link

### ISSUE THREAD

**Issue by BenMukebo** [BenMukebo/javascript-capstone#21]
This is a Project link:  `https://github.com/BenMukebo/javascript-capstone/projects/1 `,
For this project, we are only two people in our team: @BenMukebo and @mmsesay

**Comment by Georjane** [comment]
### Hello, Team ✋🏽 
Great job making a copy and setting up your Kanban board.
However, we have one change to make in order to meet all requirements for this step to be approved but you are almost there!

Required Changes ♻️

- [ ]  All cards with group tasks in the title should be assigned to someone (it does not matter to whom as you guys have the freedom to choose).

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Dipeshtwis** [comment]
# Status: Approved ✔️

## Hi @BenMukebo &  @mmsesay,

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project(check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by BenMukebo** [comment]
Thank you, We have completed the required change.
